export type IconNamesMap =
  'trash-outline' |
  'trash' |
  'add-bulleted-list' |
  'add-circle-outline' |
  'add-file' |
  'add-folder' |
  'add-headlines' |
  'add-meta' |
  'add-numbered-list' |
  'add-quote' |
  'add-square-outline' |
  'add-square' |
  'add-table' |
  'add-to-do-list' |
  'add-toggle-list' |
  'add-txt' |
  'arrow-bottom' |
  'arrow-drop-close' |
  'arrow-drop-open' |
  'arrow-left' |
  'arrow-right' |
  'arrow-top' |
  'chart-direction' |
  'close' |
  'copy' |
  'drag' |
  'drop' |
  'edit-code' |
  'favourite-outline' |
  'favourite' |
  'file-outline' |
  'file' |
  'filter' |
  'folder' |
  'home' |
  'info' |
  'kebab' |
  'like-outline' |
  'like' |
  'link' |
  'locked' |
  'market-outline' |
  'market' |
  'notification' |
  'open-close' |
  'preview' |
  'queries' |
  'rename' |
  'search' |
  'select-outline' |
  'select' |
  'settings' |
  'source' |
  'tag' |
  'template' |
  'type' |
  'unlocked' |
  'upload-outline' |
  'upload' |
  'success' |
  'error' |
  'select-arrow'

interface IIcon {
  name: IconNamesMap;
  className?: string;
}
